version: '0'

services:
  api:
    build: .
    volumes:
      - .:/usr/src/app/
      - bundle:/usr/local/bundle/
    working_dir: /usr/src/app/
    command: puma
    ports:
      - 3000:3000
    links:
    - mysql


  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=dev

  redis:
    image: redis
    ports:
      - 6379:6379
